apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: sureshaho/simple-dev-op-image-latest:v1
      ports:
        - containerPort: 8080
